disabled_rules:
  - large_tuple

opt_in_rules:
  - closure_spacing
  - closure_body_length
  - collection_alignment
  - empty_count
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - override_in_extension
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call  
  - vertical_whitespace_closing_braces
  - yoda_condition
 
fatal_error_message: error

type_name:
  min_length: 2
  max_length: 80

line_length:
  ignores_comments: true
